### ISSUE TITLE
fix: Component types become any after router integration

### ISSUE THREAD

**Issue by hawwei913** [nuxt-modules/ionic#423]
### 🐛 The bug

Enable router integration
![image](https://github.com/nuxt-modules/ionic/assets/47056525/5b252f07-87cc-42ca-ae51-8bef191f6411)

Disable router integration
![image](https://github.com/nuxt-modules/ionic/assets/47056525/2e309489-d503-441a-8389-406009347c91)

### 🛠️ To reproduce

https://github.com/hawwei913/nuxt

### 🌈 Expected behaviour

Component types still preserve after enable route integration

### ℹ️ Additional context

no issue in [v0.8.1](https://github.com/nuxt-modules/ionic/releases/tag/0.8.1)

**Comment by Jamiewarb** [comment]
If I remember reading a comment in one of Ionic's code files, I believe this is caused by Ionic router itself - they did not want to create a package dependency, and so export as type `any` instead. I'll try to find the file and link to it

**Comment by cipami** [comment]
Anyone found solution to this please? 🤞

**Comment by LouisHaftmann** [comment]
Having the same issue :(

**Comment by LouisHaftmann** [comment]
I did some testing and compared the dist output of version 0.8.1 and 0.12.1:

The problem appears to be a missing import for the `Plugin` type:

```ts
import type { Router } from "vue-router";
declare const _default: Plugin<{
  router: Router;
}>;
export default _default;
```

Everything works fine when adding the import:

```ts
import type { Router } from "vue-router";
import type { Plugin } from "#app";
declare const _default: Plugin<{
  router: Router;
}>;
export default _default;
```

probably caused by this change: https://github.com/nuxt-modules/ionic/commit/d3e0cdde35887d6cd04c1058bd8d8cc91c9ac60a#diff-d0a25ef9729c33152cdd7eaadb16811112bf8a179898e0c6d633ca86ffaa2514R184
